### ISSUE TITLE
client.ip shows 172.0.0.1, not the real client ip

### ISSUE THREAD

**Issue by dbsdsun** [fgsch/libvmod-geoip2#10]
sub vcl_recv {
    set req.http.MyIP = client.ip;
    .......

with phpinfo(), I got:
    _SERVER["HTTP_MYIP"]	127.0.0.1
    _SERVER["REMOTE_ADDR"]	161.43.220.70
    _SERVER["HTTP_X_FORWARDED_FOR"]	161.43.220.70, 127.0.0.1

How can I get _SERVER["REMOTE_ADDR"] in vcl_recv?
Thanks,

**Comment by gewaechshaus** [comment]
Hey,

http://www.harecoded.com/determining-the-real-client-ip-with-varnish-w-x-forwarded-for-2177289

Best regards,
Jan

**Comment by fgsch** [comment]
I don't know your setup but looks like you have something in front of Varnish so the connection is coming from localhost. You can try:

```
sub vcl_recv {
	set req.http.MyIP = regsub(req.http.X-Forwarded-For, ",.*", "");
}
```

Please note this is not specific to this vmod so I'd appreciate if you ask more general questions using the existing support mechanisms detailed at https://www.varnish-cache.org/support.

**Comment by fgsch** [comment]
Hope your question is answered. I will close this ticket now.
