### ISSUE TITLE
how to close geoip file in vcl_fini

### ISSUE THREAD

**Issue by dbsdsun** [fgsch/libvmod-geoip2#11]
in the example, I found

    sub vcl_init {
        new country = geoip2.geoip2("GeoLite2-Country.mmdb");
    }

I think, the geoip file should be closed in vcl_fini. Could you please show how to close it?
thanks

**Comment by fgsch** [comment]
The file is closed automatically when the reference disappears, e.g. a new VCL is loaded.
You don't need to do anything.
