### ISSUE TITLE
Please document what can be looked up

### ISSUE THREAD

**Issue by Danack** [fgsch/libvmod-geoip2#21]
Hi,

Please could you document what can be looked up through the country.lookup() api call.

For example I can see

country.lookup("country/names/en", client.ip) - apparently returns the country name in English

country.lookup("country/iso_code") - apparently returns the country code and language like 'gb-en'

What other wondrous possibilities are there?

cheers
Dan

**Comment by fgsch** [comment]
This depends on the database and as such outside the scope of this VMOD.

You could use mmdblookup to dump the content. See https://maxmind.github.io/libmaxminddb/mmdblookup.html for details.
