### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by vladbondarenko** [fgsch/libvmod-geoip2#22]
Hi Federico,

I guess libvmod-geoip2 doesnt support ipv6 from https://support.maxmind.com/ipv6-data-faq/

Do you plan to support it?

Thanks.

**Comment by fgsch** [comment]
It should just work fine if the DB you are using has the data. 

See https://github.com/fgsch/libvmod-geoip2/blob/master/src/tests/b00001.vtc#L27 for example.

**Comment by vladbondarenko** [comment]
Thanks a lot. Works for me.
