### ISSUE TITLE
Could you please suggest a way to figure out city, state using this library?

### ISSUE THREAD

**Issue by vikasbatra** [fgsch/libvmod-geoip2#28]
I am using "GeoIP2-City.mmdb" and i am able to get country code using the documentation provided along with this project. But do you have some more deep examples e.g. how to find name and iso code of city and state OR pincode OR location string ?

Thanks for creating this VMOD.

**Comment by fgsch** [comment]
Sure, I will add some examples to the wiki and update this ticket later today.

**Comment by vikasbatra** [comment]
Thanks a lot.
