### ISSUE TITLE
Getting the below error when run make

### ISSUE THREAD

**Issue by itssameermd** [fgsch/libvmod-geoip2#37]
varnishd -V output : 

varnishd (varnish-5.2.1 revision 67e562482)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS

ERROR :

make  all-recursive
make[1]: Entering directory `/opt/libvmod-geoip2'
Making all in src
make[2]: Entering directory `/opt/libvmod-geoip2/src'
/bin/python3.6 /usr/share/varnish/vmodtool.py ../src/vmod_geoip2.vcc
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -I/usr/include/varnish  -g -O2 -MT libvmod_geoip2_la-vmod_geoip2.lo -MD -MP -MF .deps/libvmod_g
eoip2_la-vmod_geoip2.Tpo -c -o libvmod_geoip2_la-vmod_geoip2.lo `test -f 'vmod_geoip2.c' || echo './'`vmod_geoip2.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -g -O2 -MT libvmod_geoip2_la-vmod_geoip2.lo -MD -MP -MF .deps/libvmod_geoip2_la-vmod_geoip2.Tpo -c vmo
d_geoip2.c  -fPIC -DPIC -o .libs/libvmod_geoip2_la-vmod_geoip2.o
In file included from vmod_geoip2.c:38:0:
vcc_if.h:12:1: error: unknown type name 'VCL_VOID'
 VCL_VOID vmod_geoip2__init(VRT_CTX,
 ^
vcc_if.h:13:5: error: expected ')' before 'struct'
     struct vmod_geoip2_geoip2 **, const char *, VCL_STRING);
     ^
vcc_if.h:14:1: error: unknown type name 'VCL_VOID'
 VCL_VOID vmod_geoip2__fini(struct vmod_geoip2_geoip2 **);
 ^
vcc_if.h:15:1: error: unknown type name 'VCL_STRING'
 VCL_STRING vmod_geoip2_lookup(VRT_CTX,
 ^
vcc_if.h:16:5: error: expected ')' before 'struct'
     struct vmod_geoip2_geoip2 *, VCL_STRING, VCL_IP, VCL_BOOL);
     ^
vmod_geoip2.c:51:15: error: expected ')' before 'enum'
 vslv(VRT_CTX, enum VSL_tag_e tag, const char *fmt, ...)
               ^
vmod_geoip2.c:63:1: error: unknown type name 'VCL_VOID'
 VCL_VOID
 ^
vmod_geoip2.c:64:28: error: expected ')' before 'struct'
 vmod_geoip2__init(VRT_CTX, struct vmod_geoip2_geoip2 **vpp,
                            ^
vmod_geoip2.c:93:1: error: unknown type name 'VCL_VOID'
 VCL_VOID
 ^
vmod_geoip2.c:126:1: error: unknown type name 'VCL_STRING'
 VCL_STRING
 ^
vmod_geoip2.c:127:29: error: expected ')' before 'struct'
 vmod_geoip2_lookup(VRT_CTX, struct vmod_geoip2_geoip2 *vp,
                             ^
make[2]: *** [libvmod_geoip2_la-vmod_geoip2.lo] Error 1
make[2]: Leaving directory `/opt/libvmod-geoip2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/libvmod-geoip2'
make: *** [all] Error 2

**Comment by fgsch** [comment]
Varnish 5.2.1 is EOL and no longer supported unfortunately.
From the README:

```
For Varnish 6.0, 6.3 and 6.4 refer to master branch. Older Varnish versions are no longer supported.
```
