### ISSUE TITLE
Incompatible VMOD geoip2

### ISSUE THREAD

**Issue by tibbon** [fgsch/libvmod-geoip2#38]
I've tried installing from tar archive, and also from master on github. Both compile, but I'm getting this problem with Varnish 6.4 either way. 

```
**** v1   CLI RX|Message from VCC-compiler:
**** v1   CLI RX|Incompatible VMOD geoip2
**** v1   CLI RX|\tFile name: /etc/varnish/libvmod-geoip2/src/.libs/libvmod_geoip2.so
**** v1   CLI RX|\tABI mismatch, expected <Varnish 6.4.0 13f137934ec1cf14af66baf7896311115ee35598>, got <USH\x81\xec\x98>
**** v1   CLI RX|('<vcl.inline>' Line 41 Pos 8)
**** v1   CLI RX|import geoip2 from "/etc/varnish/libvmod-geoip2/src/.libs/libvmod_geoip2.so";
**** v1   CLI RX|-------######----------------------------------------------------------------
**** v1   CLI RX|
**** v1   CLI RX|Running VCC-compiler failed, exited with 2
**** v1   CLI RX|VCL compilation failed
---- v1   VCL compilation failed expected success
```

The top of my VCL just has

```
import directors;
import std;
import geoip2;
```

But I've also tried it with the full path at `import geoip2 from "/etc/varnish/libvmod-geoip2/src/.libs/libvmod_geoip2.so";`

I'm using `varnish:latest` and my relevant installation steps are: 

```
ENV PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/

RUN git clone --recursive https://github.com/fgsch/libvmod-geoip2 && \
    cd libvmod-geoip2 && \
    ./autogen.sh && \
    ./configure && \
    make install && \
    ldconfig
```

**Comment by fgsch** [comment]
In order to debug this issue, I'm gonna need some info:

1. Which branch are you using?
2. Are you compiling and running in the same machine?
3. Is there any chance you have multiple Varnish versions installed?
4. Can you provide the output of `varnishd -V`?
5. Can you provide the output of `uname -a` and distribution being used?
6. Can you attach the generated config.log?

This should be enough for now.

**Comment by tibbon** [comment]
1. `devel` branch. Going to try it with `master` next
2. Yea, this is all happening in a Docker container - so I can tear down the entire thing and redo it repeatably
3. I have been pondering this. I don't _think_ so. When I search my whole filesystem for `varnishd` I only find it in `/usr/sbin/varnishd`
4. 
```
varnishd -V
varnishd (varnish-6.4.0 revision 13f137934ec1cf14af66baf7896311115ee35598)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2020 Varnish Software AS
```
5. 
```
uname -a
Linux e849c9443eb9 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
```

Using the `docker:latest` container/image, which is build on Debian: https://github.com/varnish/docker-varnish/blob/d32d16eb38cd161f0e626880cbd334da7d301027/fresh/debian/Dockerfile

6. 
[config.log](https://github.com/fgsch/libvmod-geoip2/files/4852645/config.log)

**Comment by tibbon** [comment]
To get additional logging, when I ran the `./configure` for this for this last attempt, I ran it with extra flags: `./configure CFLAGS="-Wall -Wextra -Werror"`

**Comment by fgsch** [comment]
Thanks. You should use master but for this particular error I don't think this will make any difference.

Have you tried running the tests after compiling?

I will take a look but I'm really puzzled.

**Comment by tibbon** [comment]
That's what's weird - the tests during the check phase run just fine! I'm about to meet with someone on my team and see if we can make sense of it.

**Comment by tibbon** [comment]
Huh, now on `master` I'm seeing this:

```
**** v1   CLI RX|Message from VCC-compiler:
**** v1   CLI RX|Incompatible VMOD geoip2
**** v1   CLI RX|\tFile name: /usr/lib/x86_64-linux-gnu/varnish/vmods/libvmod_geoip2.so
**** v1   CLI RX|\tABI mismatch, expected <Varnish 6.4.0 13f137934ec1cf14af66baf7896311115ee35598>, got <UH\x89\xe5H\x81\xec\xc0>
**** v1   CLI RX|('<vcl.inline>' Line 41 Pos 8)
```

I'm scratching my head as to what is reporting `<UH\x89\xe5H\x81\xec\xc0>`

**Comment by tibbon** [comment]
Ok! Got to the root of it. Or well, I got a fix that maybe someday someone will find useful. I was prior using that `docker:latest` image as my base, but I did notice your instructions say "Varnish master built from sources" which this wasn't doing. So I did that. Seems to work now! Here's my Dockerfile for future reference. It's a mess at the moment, but it's a work in progress:

```
FROM debian:buster-slim

ENV BUNDLER_VERSION 2.1.4
ENV LANGUAGE en_US.UTF-8
ARG RAILS_ROOT=/app
ARG BUILD_PACKAGES="make \
                    ruby-dev \
                    curl \
                    automake \
                    autoconf \
                    automake \
                    build-essential \
                    ca-certificates \
                    cpio \
                    git \
                    graphviz \
                    libedit-dev \
                    libjemalloc-dev \
                    libncurses-dev \
                    libpcre3-dev \
                    libtool \
                    libunwind-dev \
                    pkg-config \
                    python3-sphinx \
                    sudo"

ARG VARNISH_ROOT=/app
ENV VARNISH_SIZE 100M
ENV PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig

RUN apt update -y && \
  apt upgrade -y && \
  apt install -y $BUILD_PACKAGES

RUN git clone https://github.com/varnishcache/varnish-cache && \
  cd varnish-cache && \
  ./autogen.sh && \
  ./configure && \
  make && \
  make install && \
  ldconfig

RUN git clone --recursive https://github.com/maxmind/libmaxminddb && \
  cd libmaxminddb && \
  ./bootstrap && \
  ./configure && \
  make && \
  make check && \
  make install && \
  ldconfig

RUN git clone --recursive https://github.com/fgsch/libvmod-geoip2 && \
    cd libvmod-geoip2 && \
    git checkout master && \
    ./autogen.sh && \
    ./configure && \
    make install && \
    ldconfig

RUN apt remove -y --purge curl
RUN apt -y autoremove

COPY . $VARNISH_ROOT/
WORKDIR $VARNISH_ROOT
```

**Comment by fgsch** [comment]
Thanks for confirming it's working and sharing your dockerfile.
