### ISSUE TITLE
/usr/bin/python2.7  ../src/vmod.vcc

### ISSUE THREAD

**Issue by dbsdsun** [fgsch/libvmod-geoip2#7]
Under ~/src/libvmod-geoip2, I run make and get the following error message:
-----------------------------------------------------------------------------------------------------
Making all in src
make[2]: Entering directory `/home/ec2-user/src/libvmod-geoip2/src'
/usr/bin/python2.7  ../src/vmod.vcc
  File "../src/vmod.vcc", line 27
    $Module geoip2 3 Varnish GeoIP2 Lookup Module
    ^
SyntaxError: invalid syntax
make[2]: *** [vcc_if.h] Error 1
make[2]: Leaving directory `/home/ec2-user/src/libvmod-geoip2/src'
-----------------------------------------------------------------------------------------------------

the script can not find vmodtool.py. I have attached config.log

[config.log.txt](https://github.com/fgsch/libvmod-geoip2/files/98723/config.log.txt)

**Comment by fgsch** [comment]
Have you compiled varnish from sources or installed a package?
If it's the latter, is libvarnishapi-dev (Debian/Ubuntu) or varnish-libs-devel (CentOS/RedHat) installed?

**Comment by dbsdsun** [comment]
Thanks for you prompt reply,
At the beginning, I use the following to install varnish
       sudo yum install varnish

Then, I use the the following steps to install varnish
        git clone --recursive https://github.com/varnish/Varnish-Cache.git
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig

Now, I can not find libvarnishapi-dev nor varnish-libs-devel. I'm using amazon-linux-ami

**Comment by fgsch** [comment]
Can you share the output of `yum search varnish`?

**Comment by dbsdsun** [comment]
[ec2-user@ip-172-31-11-96 ~]$ sudo yum search varnish
Loaded plugins: priorities, update-motd, upgrade-helper
712 packages excluded due to repository priority protections
=================================================== N/S matched: varnish ====================================================
collectd-varnish.x86_64 : Varnish plugin for collectd
varnish-docs.x86_64 : Documentation files for varnish
varnish-libs.i686 : Libraries for varnish
varnish-libs.x86_64 : Libraries for varnish
varnish-libs-devel.x86_64 : Development files for varnish-libs
varnish.x86_64 : High-performance HTTP accelerator

  Name and summary matches only, use "search all" for everything.

**Comment by fgsch** [comment]
I'm confused. varnish-libs-devel is showing up. 

Are you getting an error if you try to install it?

**Comment by dbsdsun** [comment]
when I 'make' under ~/src/libvmod-geoip2

I got the following error:
     /usr/bin/python2.7 ../src/vmod.vcc
File "../src/vmod.vcc", line 27
$Module geoip2 3 Varnish GeoIP2 Lookup Module
^
SyntaxError: invalid syntax
make[2]: *** [vcc_if.h] Error 1
-----------------------------------------------
actually, it was executing 
     PYTHON  VMODTOOL  ../src/vmod.vcc

because VMODTOOL is not defined. the command become 
        /usr/bin/python2.7 ../src/vmod.vcc

Therefore, vmodtool.py is missing, I think.

**Comment by dbsdsun** [comment]
I got error when "make", therefore, I didn't "make install"

**Comment by fgsch** [comment]
Sorry, I meant to say that I'm confused because you originally said **Now, I can not find libvarnishapi-dev nor varnish-libs-devel. I'm using amazon-linux-ami**.

But your output of yum search varnish shows that the package is available to be installed.

**Comment by fgsch** [comment]
Are you getting an error if you try to install the `varnish-libs-devel` package?

**Comment by dbsdsun** [comment]
>>> Sorry, I meant to say that I'm confused because you originally said Now, I can not find 
>>> libvarnishapi-dev nor varnish-libs-devel. I'm using amazon-linux-ami.

>>> But your output of yum search varnish shows that the package is available to be installed.

At the beginning, I use "find / -name libvarnishapi-dev" and "find / -name varnish-libs-devel", and find nothing.

Actually, I have 'varnish-libs-devel.x86_64' (with .x86_64)

**Comment by dbsdsun** [comment]
This is no error when installing varnish-libs-devel package
----------------------------------------------------------------------------------------------------------
[ec2-user@ip-172-31-11-96 ~]$ sudo yum install varnish-libs-devel
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                                                                                      | 2.1 kB     00:00
amzn-updates/latest                                                                                   | 2.3 kB     00:00
epel/x86_64/metalink                                                                                  | 3.0 kB     00:00
epel/x86_64                                                                                           | 4.3 kB     00:00
epel/x86_64/updateinfo                                                                                | 465 kB     00:00
epel/x86_64/primary_db                                                                                | 3.8 MB     00:00
713 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package varnish-libs-devel.x86_64 0:3.0.5-1.16.amzn1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================
 Package                            Arch                   Version                           Repository                 Size
=============================================================================================================================
Installing:
 varnish-libs-devel                 x86_64                 3.0.5-1.16.amzn1                  amzn-main                  28 k

Transaction Summary
=============================================================================================================================
Install  1 Package

Total download size: 28 k
Installed size: 37 k
Is this ok [y/d/N]: y
Downloading packages:
varnish-libs-devel-3.0.5-1.16.amzn1.x86_64.rpm                                                        |  28 kB     00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : varnish-libs-devel-3.0.5-1.16.amzn1.x86_64                                                                1/1
  Verifying  : varnish-libs-devel-3.0.5-1.16.amzn1.x86_64                                                                1/1

Installed:
  varnish-libs-devel.x86_64 0:3.0.5-1.16.amzn1

Complete!

**Comment by fgsch** [comment]
Ok, I see the issue now.  You are installing varnish 3.0.5 but the package only works with varnish 4.0 and higher.

**Comment by dbsdsun** [comment]
I git clone --recursive https://github.com/varnish/Varnish-Cache.git , then install varnish, 
then install libmaxminddb (git clone --recursive https://github.com/maxmind/libmaxminddb)
then install libvmod-geoip2 (git clone --recursive https://github.com/fgsch/libvmod-geoip2)

still got that error when 'make'

**Comment by fgsch** [comment]
As I said, this module does not support varnish 3.0.X. It needs varnish 4.0 or higher.
The error you are seeing is due to that. 

I will amend the configure to error out earlier to make it more explicit.

**Comment by dbsdsun** [comment]
thanks for your help

**Comment by fgsch** [comment]
No problem. I will close this issue now.

**Comment by fgsch** [comment]
Actually, in commit e6f56100900759c8966f413ffe63a09f30ea1d9b I've added a check for varnish.m4.
This should be enough in this case since this appeared in Varnish 4.

**Comment by dbsdsun** [comment]
I remove old varnish
        sudo yum remove varnish

install new varnish
       cd ~/src/Varnish-Cache
       git pull
       ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig

then reinstall libvmod-geoip2
        cd ~/src/libvmod-geoip2
        git pull
        ./autogen.sh

and get the error message:
        No package 'varnishapi' found

         Consider adjusting the PKG_CONFIG_PATH environment variable if you
         installed software in a non-standard prefix.

**Comment by fgsch** [comment]
@dbsdsun Is pkg-config installed? Assuming it is, do you have a varnishapi.pc file under /usr/local/lib/pkgconfig/ ?

PS: Please next time open a new ticket since this is a different issue.
