### ISSUE TITLE
install on Amazon Linux AMI

### ISSUE THREAD

**Issue by dbsdsun** [fgsch/libvmod-geoip2#8]
I remove old varnish

        sudo yum remove varnish

install new varnish

       cd ~/src/Varnish-Cache
       git pull
       ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig

then reinstall libvmod-geoip2

        cd ~/src/libvmod-geoip2
        git pull
        ./autogen.sh

and get the error message:

        No package 'varnishapi' found

         Consider adjusting the PKG_CONFIG_PATH environment variable if you
         installed software in a non-standard prefix.

**Comment by dbsdsun** [comment]
from fgsch
----------------------------------------------------------------------
@dbsdsun Is pkg-config installed? Assuming it is, do you have a varnishapi.pc file under /usr/local/lib/pkgconfig/ ?
----------------------------------------------------------------------

@fgsch 
pkg-config is installed, I can see varnishapi.pc file under /usr/local/lib/pkgconfig/.


[ec2-user@ip-172-31-11-96 ~]$ sudo yum search pkg-config
Loaded plugins: priorities, update-motd, upgrade-helper
714 packages excluded due to repository priority protections
========================================================================================================== N/S matched: pkg-config ==========================================================================================================
mingw32-pkg-config.x86_64 : A tool for determining compilation options for the win32 target
mingw64-pkg-config.x86_64 : A tool for determining compilation options for the win64 target
perl-ExtUtils-PkgConfig.noarch : Simplistic interface to pkg-config

  Name and summary matches only, use "search all" for everything.
[ec2-user@ip-172-31-11-96 ~]$ ls /usr/local/lib/pkgconfig
geoip.pc  libmaxminddb.pc  varnishapi.pc

**Comment by fgsch** [comment]
Can you try installing pkgconfig instead via `yum install pkgconfig`?

**Comment by fgsch** [comment]
Actually, I'd expect a different error if pkg-config is missing so I guess /usr/local/lib/pkgconfig/ is not in the default list of directories to search for .pc files.

Try running `env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure`.

**Comment by dbsdsun** [comment]
wget http://pkgconfig.freedesktop.org/releases/pkg-config-0.18.1.tar.gz
then unzip ...
./configure

got this error:

    checking how to run the C++ preprocessor... /lib/cpp
    configure: error: C++ preprocessor "/lib/cpp" fails sanity check
    See `config.log' for more details.

in config.log

    |                    Syntax error
    configure:4894: /lib/cpp  conftest.cc
    cpp: error trying to exec 'cc1plus': execvp: No such file or directory
    configure:4900: $? = 1
    configure: failed program was:
    | /* confdefs.h.  */


I seems I don't have cc1plus

**Comment by fgsch** [comment]
Rather than trying that please see my other comment first. You can contact me in gitter.im too.

**Comment by dbsdsun** [comment]
run the following commands

    env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh
    ./configure
    make

got error again

    make[2]: Entering directory `/home/ec2-user/src/libvmod-geoip2/src'
    /usr/bin/python2.7  ../src/vmod.vcc
      File "../src/vmod.vcc", line 27
        $Module geoip2 3 Varnish GeoIP2 Lookup Module
        ^
    SyntaxError: invalid syntax

**Comment by fgsch** [comment]
Sorry, you need to do that for both autogen.sh and configure:

`env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh`
`env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure`

**Comment by dbsdsun** [comment]
the follow commands are passed:

    env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh
    env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure
    make
    sudo make install

Thanks for the help!!!

**Comment by fgsch** [comment]
No problem.   Glad it's building and installing now.
I will update the installation details and try to address the SyntaxError issue in configure.

**Comment by fgsch** [comment]
In retrospective, I can't really explain nor reproduce the SyntaxError when PKG_CONFIG_PATH was not set.
I get an error at configure time.

**Comment by dbsdsun** [comment]
@fgsch maybe, I was still using old ./configure result.

./configure     I missed the error message
make             I was using old configure result generated with previous commit.

I think so.

**Comment by fgsch** [comment]
@dbsdsun I considered that but did not know whether you have received an error or checked the output at configure time. Thanks for letting me know.
